### ISSUE TITLE
Identify shared email needs. Collect or design some base templates.

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#684] opened 2016-01-15 17:13 UTC
We have designed a bunch of email templates over the past year. It would be great to be more strategic about who / what the different layouts are for, and design some templates for those use cases. So that we don't have to design a new template for every campaign, product launch, event, etc.

@adamlofting mentioned @stephaniemcv will be taking over the CRM and could probably be a big help here.

For reference (we should consult @valianttry on email best practices and learnings from past campaigns): https://github.com/mozilla/donate.mozilla.org/issues/1108

**Comment by adamlofting** [comment] 2016-01-18 10:03
These were the templates when I was reviewing this mid 2015, but we've designed a built a few more templates since then: https://docs.google.com/spreadsheets/d/1Omfk2sQu25lbl9MOY_BCFYi71P4tXO4c0n7gvmCyAX0/edit#gid=731058936

**Comment by cassiemc** [comment] 2016-03-07 17:01
cc @natalieworth Will reassign you here.

**Comment by cassiemc** [comment] 2016-03-10 03:05
@natalieworth Any updates? As this was a p2 I suspect we'd like to roll this into the next heartbeat to wrap up.

**Comment by natalieworth** [comment] 2016-03-24 22:01
I've been continually updating Mozilla emails to a google slide deck to document email templates from the last year: https://docs.google.com/presentation/d/1J5Ein_yp-6tCkScDqEERQ7ZmfVnSI6gNjVYGbCFHy6M/edit#slide=id.g1273287acd_0_127

I think next step for me could be to identify/ sketch different templates that we would need in order to streamline future design/ dev process for upcoming Foundation emails (e.g. content-heavy, image based, newsletter, Mozilla standard, etc.)
cc @cassiemc

**Comment by valianttry** [comment] 2016-03-24 22:09
Love and appreciate the care that has gone into this work!

@lovegushwa knows this already (and @cassiemc and @natalieworth might know already as well) but our email strategy will be gradually more integrated with the Firefox team's strategy. This also means we share some email audience. We will want to think about our template design so that we communicate our unique brands in a way that doesn't confuse recipients.

**Comment by natalieworth** [comment] 2016-03-24 23:20
Thanks @valianttry —would be great to connect with you about the Firefox's strategy and how we can integrate into the updated templates. Would also be great to get dev feedback on any restrictions there may be in implementing the designs. I know from previous versions type, columns, and images can sometimes be an issue.

**Comment by natalieworth** [comment] 2016-03-31 20:22
@valianttry My next steps here (based on the google slide I put together) would be to parse through email types/ templates that we have used in the past and sketch some rough versions up. Then could connect with you after your back from PTO on this about which to proceed with?
@stephaniemcv I noticed above too that you are going to be taking over the CRM and I know you've helped out a lot already with the Advocacy emails, so would be great to get your insight too on email/ template needs or any restrictions on design.

**Comment by valianttry** [comment] 2016-04-01 06:21
@stephaniemcv and I met with the MoCo marketing/email team today. We agreed that we should continue to use the existing templates (@lovegushwa's latest design and color palette) for the near future. The brand team's work is underway, and it seems like it might be wasted effort to continue to iterate when the outcome of the brand work is unknown (and could lead to changes). We already have 4 - 5 new template designs, but we may need a couple of additional iterations (for instance, a version with a callout box aligned top right for fundraising). 

@natalieworth perhaps you and @stephaniemcv can connect while i'm out on a fundraising variant?

**Comment by natalieworth** [comment] 2016-04-01 19:45
@valianttry @stephaniemcv That all sounds good. I'll hold off until the MoCo branding is clearer and see if we need to update the templates at a later time in order to streamline the designs between MoCo/ MoFo. If we need different iterations, I can update the existing one's from the campaign :)

**Comment by hannahkane** [comment] 2016-04-04 20:22
moving to current heartbeat, so we can close the last one

**Comment by hannahkane** [comment] 2016-04-12 15:23
rolling to current heartbeat, so this doesn't get lost

**Comment by natalieworth** [comment] 2016-04-18 18:19
Thanks @hannahkane — this is currently on hold until we get the upcoming Mozilla brand established in order to not repeat work. There are email templates that Jordan has designed which we are going to continue using for the Advocacy work and update as needed until the branding is completed. We could close and then reopen this issue when MoCo branding is further along?

**Comment by hannahkane** [comment] 2016-04-18 22:45
@natalieworth - sure. feel free to close and then reopen, or just put in a future milestone if you'd like.

**Comment by natalieworth** [comment] 2016-05-12 00:03
@hannahkane I don't anticipate moving forward with this until the brand unification is created along with the updated Mozilla future branding. Going to close for now and will reopen or create a new ticket based on the work the Foundation is doing along with MoFo's future style guides. :)

**Closed by natalieworth** 2016-05-12 00:03 UTC
Labels: audit, betterfaster, p2, Size: large, Status: on track
