### ISSUE TITLE
Did we stop supporting Popcorn makes?

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#478] opened 2015-06-08 09:33 UTC
I have several users asking why their Popcorn makes are no longer loading. One user said his no longer loaded YouTube videos. In trying to confirm, I have mixed results - for my makes it seems like the more recent the make, the more likely it loads. 

Have we changed something in the last week? I know we are continuing support for Thimble makes, but I'm not sure what to tell folks regarding Popcorn...

**Comment by jgmac1106** [comment] 2015-06-08 14:38
@LauraHilliger Yeah I just logged into webmaker, clicked on tools, and clicked on Popcorn. In all three places I did not see a deprecation message. I thought the RIP date was June 16th and a deprecation message was supposed to be added but I could be wrong.

**Comment by OpenMatt** [comment] 2015-07-06 16:54
I believe this ticket is a dupe of: https://github.com/MozillaFoundation/plan/issues/465

**Closed by OpenMatt** 2015-07-06 16:54 UTC
Labels: communication
