### ISSUE TITLE
Recreate "labels" from Bugzilla in Github

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#256] opened 2015-01-21 23:10 UTC
Thinking specifically of:
* resolved: won't-fix
* resolved: duplicate
* needinfo (could change assignee to the person it's requested of)
* R? (so status of waiting for a review is clear, could also change assignee here).

These were historical-type labels that were interesting when you were trying to get caught up on an issue you hadn't been involved in from the beginning.

And it coule make the transition from Bugzilla to Github easier on some folks. Though maybe we're already past that point. cc @OpenMatt @davidascher

**Comment by davidascher** [comment] 2015-01-27 01:44
My hope is that something like plzkthx can deal with needinfo + review
flows, if & when we integrate it in build.w.o. Labels don't work for this
because they have to be tied to an individual.

Resolved won't fix I don't think is particularly useful -- we can just
close a ticket with a comment as to why it's being closed.

Saying "duplicate of #123" and closing the bug is how duplicates are
usually handled in github.  It seems to work OK in practice, no?

**Closed** 2015-12-22 18:57 UTC
Labels: process
