### ISSUE TITLE
Audit Email templates

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/plan#758] opened 2016-02-29 23:11 UTC
Gather existing and new email templates.

**Comment by natalieworth** [comment] 2016-02-29 23:19
cc @cassiemc Created a new issue for this as I couldn't find an existing one in the plan repo, but can delete/close if I've made a duplicate ticket somehow.

**Comment by cassiemc** [comment] 2016-03-07 17:01
Dupe of #684

**Closed by cassiemc** 2016-03-07 17:01 UTC
Labels: p2, Status: on track
