### ISSUE TITLE
[Feb 12] Create new NetGain Partnership site

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#703] opened 2016-01-28 14:58 UTC
There's a potential we could outsource this work, but we need to decide by Monday Feb 1. cc @davidascher @simonwex 

**Deadline:** Feb 12 (launch Feb 16)

From @samanthaburton:

> It's this website: http://netgainchallenge.org/ part of the NetGain partnership between 5 foundations, which Mozilla helped start last year and is leading this year in partnership with the Knight Foundation.

> There's a plan to release a research report and announce a series of grants in the coming weeks. Initially, plan was for the report to go out next week and the grants to be announced later Feb/Mar. However, we've decided that the website needs to be updated first - it's basically completely inaccurate! But there's a bit of a rush, as they would like to stick as close to the original timeslines as possible.

> Also, due to the way the website was designed, we can't just update it as it is - we need to create a whole new (quick & dirty, but still new) site.

> This would include:
* simple front page refresh explaining NetGain (includes para on 2015 tech talent pipeline theme / freedman report; para on emerging 2016 theme; prominent link to our initial manifesto in plain HTML (not PDF)
* a page with the NetGain manifesto in HTML (not just .pdf)
page for Freedman Report
* A history page explaining how we got here / where we're going
* Archive / lower profile of the NetGain Challenge submissions page -- or kill it. Probably kill it.

**Comment by hannahkane** [comment] 2016-01-28 18:16
If this is truly urgent, we can reassign a designer from MLN. Would prefer not to reassign devs, though.

**Comment by davidascher** [comment] 2016-01-28 19:07
We need to understand who controls that domain today.

My understanding is that the priorities are as follows:

1) the content is out of date and needs to be updated
2) there’s a hard, and near deadline
3) anything else.

In particular, this is a small audience site, but the audience is high influence.

We should not add fancy untested technology given the timeline, especially as we don’t expect dynamic content in the near term.

**Comment by samanthaburton** [comment] 2016-01-28 20:17
The Ford Foundation has control of the domain, and we're working with them on the revamp so can easily get access. I'm not sure about hosting. 

RE: priorities
- Only piece I'd add to David's list is that the current website has a terrible UX and you can't change all the elements - hence the suggestion to create a new site, quick & dirty, on an easily customizable solution like Wordpress (as David rightly said, no need for fancy untested tech)
- #1 is already underway - new copy has been approved by both Mark & I, and Lori from Ford will be leading on coordinating finalization with other partners. So content creation doesn't need to be in this scope of work.
- If you do take the project on, I'll connect you with Lori and Jen at Spitfire, who worked on the site last year (when it was created) and have been more involved in the comms for NetGain to date. Spitfire is also supporting on the copy writing for this and project management for this + another NetGain related comms project.

Apologies for being unable to attend the meeting tomorrow, and also for being slow to respond next week. If you need to reach me, the fastest way is likely to be to call or text 416-877-0710 - please don't hesitate to give me a shout if you need anything. Thank you!

**Comment by hannahkane** [comment] 2016-01-28 20:23
If we're going to build a Wordpress site, I'd suggest we hire a contractor with Wordpress expertise.

Which strategic labels can we apply to this ticket (orange and blue labels)? Wondering where this fits in the strategic plan.

**Comment by samanthaburton** [comment] 2016-01-28 20:36
Added the strategic labels I think apply!

If your team ends up recommending that we hire a contractor for a Wordpress (or another plug-and-play) site design, we'll just go with the 'external' option (we have 2 quotes from contractors already, who'd work directly with Spitfire - so it would take the project off your plate).

Let me know what you think the best route it. Thank you!

**Comment by cassiemc** [comment] 2016-01-28 20:59
@samanthaburton Does it actually need to be wordpress? Will let @simonwex chime in but suspect that adds a bit of dev time, and if this will only be updated every so often that might make matters more complex than they need to be. How often / who will need to make updates?

Also, id your quotes include both design and dev? Ok to separate them out? I think that design might be possible here, but it'd be good to get more guidance on the appropriate look and feel, ie. how closely aligned to Mozilla's brand should this be.

**Comment by cassiemc** [comment] 2016-01-28 21:15
One other flag – designing UX and UI *and* shipping this in one two week heartbeat with external stakeholders we haven't worked with before might be a challenge.

**Comment by simonwex** [comment] 2016-01-28 22:15
From an engineering-team perspective, I think it'd be best if we use external resources for this. One of our current efforts, #fasterbetter is to lay the groundwork to be able to produce these kinds of sites without any (or very little) bespoke work. – We're not there yet. I don't think we'd learn anything from building this site, and it would distract from more strategic goals of being able to inexpensively produce and manage them.

It might be worth thinking of this update a bit differently. What are the minimum changes we require now? Can we have those changes made now and later integrate with our CMS strategy to ensure future updates are simpler?

@samanthaburton, do you know the current codebase lives?

**Comment by samanthaburton** [comment] 2016-01-28 22:56
Hey everyone - taking all your thoughts into account, I think going external makes the most sense. If you're cool with that, I'm going to move to put that in motion. Thank you so much for the depth of thought and feedback, especially on such a tight timeline.

re: your question @simonwex - the problem is that the current site is locked in - we can't even make the minimum changes without changing the CMS (I have no clue why it was built this way...) 

Here's what we know (taken from an email from the comms company) -

"We are seriously constrained as to what can be done on this site. This image tells the story the best: Screen Shot 2016-01-26 at 9.20.00 AM.png.  The green boxes indicate what can be edited. Even then, the only edits that can be made are what the text says — we cannot control the layout or anything else.

Below is a breakdown, point by point, on what I asked about:

- Header where it says: Participate in the NetGain challenge. Subtext can be edited, but the main text is uneditable.
- New text on top of front page: see above
- Archive or kill lower portion of homepage — the NetGain submissions page. This is deeply integrated into the CMS and appears on every single new page, and no way to turn it off.
- New page that contains the declaration as html: Developer can create a new page, but is restricted due to the above reason. He also has very minimal control over the page itself. Just a restricted WYSIWYG-ish editor.
- New page to house a new report they are releasing: (see above)
- New page explaining history: (see above)"

**Comment by simonwex** [comment] 2016-01-29 05:43
@samanthaburton I'd like to help steer a few requirements we give to the external group. At minimum the source code should be available to us to ensure we're not painting ourselves into a corner again.

**Comment by samanthaburton** [comment] 2016-01-29 16:21
@simonwex sounds good - I'll loop you into the thread, and you can share your thoughts directly with Spitfire. 

Thanks very much again, everyone!

**Closed** 2016-01-29 16:22 UTC
Labels: Convening, Learning, Networks

**Comment by cassiemc** [comment] 2016-01-29 16:44
Works for me too, thanks @samanthaburton. If there are any questions about brand, we can definitely do a design review in-house no problem.
