### ISSUE TITLE
Update advocacy site w. fellows

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#370] opened 2015-03-02 23:42 UTC
When the Open Web Fellows are announced in April, we'll need to update https://advocacy.mozilla.org/
Driver: @edrushka
Design: @iamjessklein 
Copy: @kevzawacki
Dev: @alicoding 
Decision-maker: @Melechuga 
Consulted: @DaveSteer @valianttry 
Informed: @HPaulJohnson 

Design Deadline: May 22
Build Deadline: June 3
Track the individual tickets here: https://github.com/MozillaFoundation/movement-building/milestones/Update%20Advocacy%20site%20with%20fellows

**Comment by Melechuga** [comment] 2015-03-12 21:35
Can the RASCI be changed on this one so that @melechuga and @valianttry are switched? Melissa is the decision maker, and Andrea can be consulted (along with Dave) for this. Thanks!

**Comment by edrushka** [comment] 2015-03-12 22:19
Done! And you now have the coveted edit pencil, so feel free to change again as needed.

**Comment by DaveSteer** [comment] 2015-03-25 17:45
Let's add a deadline for this. @Melechuga can you specify? Seems like it needs to be ready by 1st/2nd week of April.

**Comment by edrushka** [comment] 2015-03-25 23:33
I added the deadlines above: Design Deadline: April 10 Build Deadline: April 22

**Comment by Melechuga** [comment] 2015-03-31 21:47
Attaching logo images for @iamjessklein that were recently designed by Luke. These will be used for the swag, and can also be used on the Website where appropriate. Thanks! 
![logo-bottle](https://cloud.githubusercontent.com/assets/5815317/6930074/e3801ffa-d7b4-11e4-8375-6725b055361b.png)
![logo-hoodie](https://cloud.githubusercontent.com/assets/5815317/6930075/e58d7ec8-d7b4-11e4-9104-5bd53f74e93f.png)

**Comment by Melechuga** [comment] 2015-03-31 21:48
Oh, the second one is a transparent + white logo.

**Comment by iamjessklein** [comment] 2015-03-31 23:24
and understated.

**Comment by OpenMatt** [comment] 2015-04-07 15:15
I'll take over as Driver on this one while Erika Druhska is away

**Comment by OpenMatt** [comment] 2015-04-07 17:00
### NOTE: Late-breaking news: we're pushing back the ship date 
Note: the Advocacy Team has hit a snag with the Fellowship selection process. So we'll need to postpone the ship date by a week or so. @Melechuga will update here as soon as she knows more.

What this means:
1) **Complete the design work.** Using dummy photos and text. Let's complete the design work anyway. Then just flow in finalized bios and photos once we have it. 
2) **Hold on the build piece.** Until the blocker is cleared.

**Comment by iamjessklein** [comment] 2015-04-07 17:38
thanks for the Bloomberg-style update, @OpenMatt

**Comment by OpenMatt** [comment] 2015-04-13 15:20
* Moving to next heartbeat, because of delay mentioned above.
* @iamjessklein : what's the status on the page design? This could be staged in WordPress with dummy photos and copy, then @Melechuga can update it with real content as she gets it.

**Comment by iamjessklein** [comment] 2015-04-13 16:55
Hey, with the new advocacy work for surveillance, I didn't get far on this (just the first page promo spot) and the initial sketching.

**Comment by edrushka** [comment] 2015-04-13 20:38
@Melechuga any ETA for the revised launch date?

**Comment by Melechuga** [comment] 2015-04-13 22:40
Hey @edrushka - Not yet; still working on getting all of the Fellows in a row. Will update as soon as I know. Thanks for being on top of it!

**Comment by edrushka** [comment] 2015-04-15 21:28
Looking like this will launch at the beginning of June. (This is unconfirmed, so we should be prepared to ship sooner if things change.) Adjusting the dates & milestones to reflect this timeline.

**Comment by edrushka** [comment] 2015-05-01 20:53
Any updates on timing @Melechuga?

**Comment by Melechuga** [comment] 2015-05-04 18:25
We're going to stick with the early June timeline. I'm in the process of collecting bios + photos now. Thanks!

**Comment by edrushka** [comment] 2015-05-04 19:08
Super. Please add an exact date to this ticket when you have one.

**Comment by edrushka** [comment] 2015-05-04 20:37
Assigning @alicoding to this cc @simonwex

**Comment by edrushka** [comment] 2015-05-08 22:22
Alright, this project is BACK ON!
Jordan will finishes Jess' design and @alicoding is on point for the build. Hurray!

**Comment by lovegushwa** [comment] 2015-05-16 09:33
@edrushka @cassiemc @Melechuga @alicoding 

Please review the current drafts on red-pen by Monday morning if possible. (Ali needs to start with development on Tuesday. Sorry to those on holiday!) 

I have a few graphic pattern ideas I will drop in a bit later but they will not effect the layout, color or typography.

https://redpen.io/p/eabfb20a45f2be9771

**Comment by Melechuga** [comment] 2015-05-18 17:06
@lovegushwa These are great! Have put comments in the redpen. Thank you.

**Comment by lovegushwa** [comment] 2015-05-19 23:49
R? @edrushka @cassiemc @Melechuga @alicoding @vazquez 

The final files are up on redpen to review. If it's good to go without any changes @alicoding will get moving right away with development.
https://redpen.io/p/vj2e71fb96b588fcf9

![open-web-home-home-final](https://cloud.githubusercontent.com/assets/12228435/7716396/87d76d1c-fe46-11e4-97fd-1ff089149755.jpg)
![open-web-home-fellows-768-nophoto-final](https://cloud.githubusercontent.com/assets/12228435/7716400/8b5178de-fe46-11e4-97a4-3a82adc98ec2.jpg)
![open-web-home-home-360](https://cloud.githubusercontent.com/assets/12228435/7716403/8fe1bf80-fe46-11e4-9843-c154863fbefe.jpg)
![open-web-home-fellows-360](https://cloud.githubusercontent.com/assets/12228435/7716404/93600c3e-fe46-11e4-847f-ec25a63af2f5.jpg)

**Comment by Melechuga** [comment] 2015-05-19 23:59
@lovegushwa This looks amazing; thanks for incorporating the changes.

**Comment by vazquez** [comment] 2015-05-20 13:22
@lovegushwa Left my comment in Redpen :+1:

**Comment by OpenMatt** [comment] 2015-05-26 16:01
status?

**Comment by edrushka** [comment] 2015-05-26 16:07
Jordan has completed design and team has signed off. Ali is 90% done the build. Will be ready to ship next week, timed with the announcement of the fellows.

**Comment by Melechuga** [comment] 2015-06-01 18:44
Hey @edrushka Thanks for keeping us updated. Just wanted to touch-base and make sure this was still on track; shipping on Wednesday, June 3rd right?

**Comment by edrushka** [comment] 2015-06-01 19:38
@Melechuga Yup! Here it is on staging: http://alicoding.github.io/advocacy.mozilla.org/open-web-fellows/
@lovegushwa will do (I think, has done this already) a final design review. @alicoding is getting code review now. All we need is your signoff!

**Comment by Melechuga** [comment] 2015-06-01 23:40
Thanks @edrushka. The design looks a bit different... @lovegushwa: I thought we went with a slightly smaller triangle? Also, could we make the picture/circles a uniform size, and perhaps make the quotations line up with the rest of the text? I like that the different size + color make them stand out, but perhaps that's all we need? Thanks.

**Comment by lovegushwa** [comment] 2015-06-02 00:34
Hi @Melechuga , the triangles are smaller in the implemented design (on the left). Could you elaborate on "Also, could we make the picture/circles a uniform size?" the circles are not all the same size?
![screen shot 2015-06-01 at 5 28 25 pm](https://cloud.githubusercontent.com/assets/12228435/7926192/b7c4cbe0-0883-11e5-8d46-c770e111f98e.png)

**Comment by Melechuga** [comment] 2015-06-02 16:38
Hi @lovegushwa on http://alicoding.github.io/advocacy.mozilla.org/open-web-fellows/ the design looks different. Perhaps that's something that @alicoding is taking care of?

**Comment by Melechuga** [comment] 2015-06-02 17:25
@alicoding Links for logo farm:
ACLU: http://aclum.org/
Amnesty International: https://www.amnesty.org/en/
APC: https://www.apc.org/
Free Press: http://www.freepress.net/
OTI: https://www.newamerica.org/oti/
Public Knowledge: https://www.publicknowledge.org/

Thanks!

**Comment by edrushka** [comment] 2015-06-04 22:30
Update:
- Ali has finished building and it's ready on staging: https://advocacy.herokuapp.com/open-web-fellows/
- Announcement date got pushed to Monday June 8
- We noticed some jankiness when site temporarily went to prod. @alicoding is investigating.

**Comment by Melechuga** [comment] 2015-06-04 22:53
Thanks!
Just noticed a few small spelling errors in the copy; please make sure to copy/paste from the google doc (https://docs.google.com/document/d/1Ev0DkdQVM3iP1_R8G5rjwHaiSmfSe1kqBiRwnEjwWPc/edit). 

* "emrging" in the intro paragraph; should be "emerging"
* Last sentence of first paragraph should be "As threats to digital freedom proliferate, it’s critical to have capable leaders." There seems to be an extra period.
* "internet" in logo farm paragraph should be capitalized.
* In Gem Barrett's paragraph, "specialises" should be "specializes"

**Comment by OpenMatt** [comment] 2015-06-05 16:09
* Washington Post is linking to this on Monday -- so need to ensure bugs fixed by then

**Comment by KevZawacki** [comment] 2015-06-05 18:16
Just to clarify, the Washington Post piece is still in the early stages — it won't be published Monday.

**Comment by edrushka** [comment] 2015-06-05 19:09
Thanks Kevin.
@Melechuga can you please confirm that the OWF site changes should go live on Monday June 8?

**Comment by Melechuga** [comment] 2015-06-05 19:44
Hi @edrushka Yes, I can confirm that changes should go live Monday June 8th. However, can we make sure the copy is corrected and reflects the content on the googledoc linked above (https://docs.google.com/document/d/1Ev0DkdQVM3iP1_R8G5rjwHaiSmfSe1kqBiRwnEjwWPc/edit)? Thanks.

**Comment by edrushka** [comment] 2015-06-05 19:46
@alicoding you've already fixed the copy on staging, correct?

**Comment by alicoding** [comment] 2015-06-05 20:09
@edrushka yep and that should be up on my staging site to test :)

**Comment by Melechuga** [comment] 2015-06-05 20:10
@alicoding Just had another look; thanks for the edits. We have one last edit from our Ford partners: the very first line should read: "The Open Web Fellows program — a collaboration between the Ford Foundation and Mozilla" ... Thank you! 

@edrushka All set! Thanks for rescheduling the launch. I'm announcing this at the Monday meeting -- and we'll have blogs/tweets published -- so if it's up by then, that would be perfect.

**Comment by OpenMatt** [comment] 2015-06-08 13:45
@alicoding Dave Steer is reporting some formatting issues with the Fellows page. I just took a quick look -- looks fine to me in FF and Chrome, but some weird left-adjust formatting issues in Safari. Like this: 
https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/43696lg8.png

* Washington Post may be linking to this page today -- crucial that its ship shape. Can you take a quick look?

**Comment by alicoding** [comment] 2015-06-08 14:05
I've updated the copy on the first line as @Melechuga requested and fixed Safari issue that @OpenMatt reported.

@jbuck and I did update the site and made sure its all looks good as expected and it should be ready to go \o/

Please test and report by looking at this url from now on. http://advocacy.mozilla.org/

**Closed** 2015-06-18 18:00 UTC
Labels: advocacy, p1
